- util/util.go
Go-carbon expects to see either X-CTX-CarbonAPI-UUID or
X-CTX-CarbonZipper-UUID, so let's give it one of those.
> Make context header consistent with other projects

- cmd/carbonapi/main.go
Also, return the current host value, instead of a map
> Register limiter use metric with graphite

- cmd/carbonzipper/main.go
- pkg/backend/net/net.go
- pkg/backend/rpc.go
- pkg/types/types.go
A /render request that would return no data returns a 404 response.
A /metrics/find request that found nothing has to return a 200 response
with an empty body to make graphite-web 0.9.12 (which we still run in
production) happy with its life.
Both situations claim that a 404 client error happened to our
monitoring.
Some combination of this may make the reader unhappy, but such is life
in a land where we control none of the APIs we need to speak.
> Distinguish 4XX from 5XX errors in carbonzipper

- expr/functions/moving/function.go
- expr/functions/movingMedian/function.go
On empty responce (no metrics) we get panic on moving and movingMedia functions. Add check for this.
> Fix moving empty

- app/carbonapi/api.go
Add log referer for slow requests (for simple identify slow grafana dashboards)
> log referer for slow requests

- expr/expr_test.go
- expr/functions/nonNegativeDerivative/function.go
- expr/functions/perSecond/function.go
It works in a way similar to maxValue: when the counter wraps, instead of
producing a null value, it computes the difference assuming the counter wrapped
to minValue.
This implements the same logic as was added to Graphite in
PR #2375 (https://github.com/graphite-project/graphite-web/pull/2375).
> Add a minValue option to nonNegativeDerivative and perSecond

- app/carbonapi/http_handlers.go
- expr/types/types.go
- expr/types/types_test.go
The CSV output of carbonapi consists of lines of the form:
"metric.name",YYYY-MM-DD hh:mm:ss,value
The time is the epoch timestamp of the metric datapoint expressed in the
local time zone.
When the "tz" option is set in the configuration file, or when a user
passes in a "tz" URL parameter, we should express the timestamp in that
time zone.
> CSV output respects timezone parameter

- app/carbonapi/http_handlers.go
- cfg/api.go
It currently returns no data, which would need to be changed once we start
supporting tags.
2. Add config to override /version with specific graphite version. This
is added to support overriding the actual graphite version with
something needed for grafana for now. It allows us to get integrated
function docs in grafana.
> 1. Add handler supporting grafana requests for graphite tags.

- expr/functions/moving/function.go
Becouse data was sampled to 10 min on query with long data range (over 30 days), for functions movingXyz (like movingMax(Series, '3min'))  windowSize == 0 and I'm get panic at (*Windowed).Push.
> fix movingXyz error on intervals greater than 30 days

- app/zipper/api.go
- pkg/backend/net/net.go
Since rolling out the pkg/backend refactoring to carbonzipper, we've seen a 100x increase in the number of open TCP connections per frontend host. This is accompanied by a similar increase in running goroutines, most of which are waiting on read- and writeLoops in the net/http library code.
I'm not able to explain this increase by staring at the code, and it seems to cause some problems for our surviving Python frontends when they try to connect to carbonzipper.
These couple of patches attempt to address the issue in two ways: We are extra careful about reading and closing response bodies, as not doing that is one source of TCP connection leaking in net/http; and we impose a timeout of 3 seconds on idle connections, after which they will be closed.
In testing, this has shown to be …
> Close long-living idle connections

- expr/functions/cairo/png/cairo.go
Fixes #41
https://github.com/graphite-project/graphite-web/blob/0.9.12/webapp/graphite/render/glyph.py#L560-L563
> Mimicking graphite-web margin indentation for graphOnly=1

- doc/functions_diff.sh
This adds a script that:
1. calls `/functions` endpoints of both **carbonapi** and **graphite-web**
2. parses their outputs
3. prits the difference in supported functions that can be easily added to the compatibility documentation
> Added script for generating difference in functions

- app/carbonapi/app.go
- app/carbonapi/metrics.go
- app/carbonzipper/app.go
- app/carbonzipper/metrics.go
- cfg/common.go
- cfg/common_test.go
- pkg/backend/net/net.go
- pkg/types/types.go
Added separate request duration histograms for `/find` and `/render` endpoints both in `carbonapi` and `carbonzipper`. This will allow us to draw better insights and have better visibility.
This resolves #79
> Per-endpoint request duration histograms for /find and /render

- pkg/backend/net/net.go
This fixes #34 both for `carbonapi` and `zipper`.
> Allow application/octet-stream to be used as protobuf content type

- app/carbonapi/http_handlers.go
- app/carbonzipper/handlers_test.go
- app/carbonzipper/http_handlers.go
- pkg/backend/rpc.go
- pkg/backend/rpc_test.go
- extracted error logic from shared code to `api` and `zipper` separately
- added unit tests for errors fan-in
- changed error logic for `finds`
- all not-found -> not found
- all mixed errors -> internal server error
- some backends succeeded -> success
- not found returns `200` code
See commit messages for more info
> Errors refactoring

- .travis.yml
The *gcc* linking with `cgo` fails on go version `1.11.7`, but succeeds on `1.11.6`. This fixes the used `1.11.X` version to be `1.11.6`. This should fix all the failing CI.
> Fixed version for go 1.11.X to be 1.11.6

- app/carbonapi/app.go
- app/carbonapi/app_test.go
- app/carbonapi/http_handlers.go
- cfg/api.go
- pkg/backend/rpc.go
1. Refactored `api` from having multiple back-end semantics but using only one to having single back-end semantics
2. This allowed to remove some obsolete code: filters, checks, etc.
3. The error logic in `api` became much simpler, clearer, and easier to handle
4. `200` is returned for not found; not found is returned when back-end returns not found
> Second stage of error-related refactoring

- app/carbonapi/app.go
- app/carbonapi/http_handlers.go
- app/carbonapi/metrics.go
- app/carbonzipper/app.go
- app/carbonzipper/http_handlers.go
- app/carbonzipper/metrics.go
- pkg/backend/net/net.go
- pkg/backend/net/net_test.go
- pkg/types/types.go
Added *Prometheus* metrics to count context cancels due to timeouts or manual cancels:
- in `api` it counts request cancels both for main request and sub-requests to `zipper`
- in `zipper` it counts main request context cancels. It is to be decided how to count partial cancels in multiple requests to backends
> Added metrics for context cancellation counting

- expr/functions/cairo/png/pixel_ratio.go
I'm not a golang developer, but after a lot of fighting with the build,
I *think* this restores the option to build this without libcairo.
> Fix builds without cairo

- app/carbonapi/http_handlers.go
- app/carbonapi/http_handlers_test.go
…e.g. if there are 3 targets and one fails, we still return a success with the data for 2 successful targets. Error handling is changed accordingly. Separate targets fail if at least one request fails with an error different from not-found.
> Refactored render handler for api. The requests now fail per-target.

- app/carbonapi/http_handlers.go
> Took into account errors returned during metrics expansion. Added logging

- app/carbonapi/app.go
- app/carbonapi/http_handlers.go
- app/carbonapi/http_handlers_test.go
- carbonapipb/carbonapi.pb.go
- some expression parsing cases are treated as wrong reqeusts now in ender handler in api
- added additional error info
- fixed http code logging: by default there is no code; substituting code for 200 disabled
- generic refactoring
> Continuation of errors refactoring

- app/carbonzipper/handlers_test.go
- app/carbonzipper/http_handlers.go
- made error merging in zipper more liberal: now at least 3 backend failures are needed along with other all being 404 to result in 500. Before it was 1.
- logging improvement
Note: this is a temporary solution. The real one is to add replica semantics to zipper backend cluster config
> Errors on zipper are more resilient to backend failures

- app/carbonapi/http_handlers.go
> No find preflight is sent in api when there are no globs in the metric

- README.md
Build process requires pkg-config to be installed. Since it is not obvious step makes sense to include its installation steps into documentation.
> updated documentation build steps with pkg-config note

- config/carbonapi.yaml
removing unused idleConnections
placing keepAliveInterval from the upstreams section where it was
silently ignored the top
> fixing errors in default config to reflect the state of code

- app/carbonzipper/handlers_test.go
- pkg/types/encoding/json/encoding.go
the /info endpoint is mostly used by humans and somehow we missed
that part of reply from carbonserver which tells us a xFilesFactor of
a whisper archive. This makes said humans sad. Fixing that.
> bringing back xFilesFactor field to json info decoder

- app/carbonapi/app.go
- app/carbonapi/http_handlers.go
- app/carbonapi/metrics.go
- docker-compose.yaml
This metric is a good measure of `carbonapi` performance that is corrected for the request weight.
> Added metric for render request durations per point pulled as an exponential histogram.

- app/carbonapi/app.go
- app/carbonapi/http_handlers.go
- app/carbonapi/metrics.go
Adds prometheus latency metrics for render requests, dividing them into two branches, simple and complex, based on the heaviness of the requests, measured in total metrics queried.
> Prometheus latency metrics for render requests

- app/carbonapi/http_handlers.go
- carbonapipb/carbonapi.pb.go
This is currently broken for multi target requests.
> Fix send globs in api access logs

- .golangci.yml
- Makefile
I tried to create a meaningful project local config in .golangci.yml, but of
course this is a matter of taste and debate.  Most of the settings come from
the default golangci-lint config file.
As of now golangci-lint finds quite a bunch of issues.  IMHO they're all worth
investigating.  I have explicitly exluded "composite literal uses unkeyed
fields" in test files as this style is used widely in the table driven tests.
The invocation via make shows only issues that are introduced since the
merge-base of this commit on the master branch in order to make the
introduction painless in CI pipelines etc.
/fixes: #189
> lint: use golangci-lint, initial project config

- .gitignore
- COMPATIBILITY.md
- expr/functions/glue.go
- expr/functions/timeLag/function.go
- expr/functions/timeLag/function_test.go
Given two monotonically non-decreasing time series (series1,series2), for every datapoint of series1 it computes the time difference required for series1 metric to achieve value of series2.
The easiest way to vizualize its correct work is to produce some ramdom
monotonnically increasing metric. Let's call it 'local.random.diceroll'
and then render the following url: render?target=timeLag(timeStack(local.random.diceroll,'1min',0, 7), local.random.diceroll)&from=-10m
Even though metric values are random, the resulting graph should look like horizontal lines precisely matching time offsets passed to timeStack function
> Add timeLag function for computing a time lag

- app/carbonapi/http_handlers.go
The problem was that iteration with `range` doesn't go through indexes
of the array added inside the loop. Therefore all the new targets
returned by rewrite functions were appended to `form.targets`, but they
were not processed afterwards
> Fix applyByNode function

- app/carbonapi/app.go
- app/carbonapi/http_handlers.go
Find requests in carbonapi did not use caching till now. No more. The cached find requests will also be used when making find requests as part of render requests.
> cache find requests

- app/carbonzipper/app.go
- app/carbonzipper/http_handlers.go
- app/carbonzipper/metrics.go
- cfg/common.go
- cfg/common_test.go
- cmd/carbonzipper/main.go
- config/carbonzipper.yaml
- pkg/backend/net/net.go
- pkg/types/types.go
Instrumenting zipper with per cluster/host performance metrics. 
We first changed configuration to include cluster info, then decorated zipper prometheus metrics with cluster information.
> Instrumenting zipper with per cluster/host performance metrics. 

- app/carbonapi/app.go
- cmd/carbonzipper/main.go
We had two issues here:
zipper was declaring two flags for -pid:
```
Usage of carbonzipper:
-config string
config file (yaml)
-pid string
pidfile (default: empty, don't create pidfile)
-pidfile string
If specified, write pid to file.
```
It was also using the "pid" flag before parsing the flags.
api was saving the pid only if it was specified in config file, not if it was specified in command line(even if it has the -pidfile argument).
> fix pidfiles:

- app/carbonapi/app.go
- app/carbonzipper/app.go
When trying to restart process using -USR2 new process start would fail
because old process was still listening on prometheus endpoint.
To fix this I added prometheus endpoint to the list of ports handled by
grace.
I also stopped registering prometheus metrics in a separate
routine. From what I tested this didn't seem to cause any issues
> fix grace reload usage.

- expr/functions/averageSeries/function.go
- expr/functions/diffSeries/function.go
- expr/functions/groupByNode/function_test.go
- expr/functions/stddevSeries/function.go
Fix auto-complete suggestions for groupByNode #232
https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.averageSeries states that averageSeries is an alias for aggregate with aggregation average. Therefore "average" method is also added to method list of github.com/bookingcom/carbonapi/expr/averageSeries
Same applied for "diff" and "stddev", which are also alias for "diffSeries" and "stddevSeries" respectively according to graphite documentation.
> auto complete group by node

- cache/cache.go
> Goroutines were blocked if reqeuests were timed out. Fixed.

- app/carbonzipper/app.go
- app/carbonzipper/metrics.go
- cfg/common.go
- cfg/common_test.go
- config/carbonzipper.yaml
- pkg/backend/net/net.go
- pkg/types/types.go
This fix enhances the configuration to include dc info to support the structure of "DC > Clusters > Backends", and include the DC of Backend in performance metrics. Previous configurations for "backends" and "backendsByCluster" are still supported.
> Fix #245: Instrument zipper with per dc/cluster/host performance metrics

- docker/go-carbon/Dockerfile
- docker/go-carbon/go-carbon.conf
- intervalset/intervalset.go
Fix integration tests. Update links to point to the new location.
Related commit:
https://github.com/go-graphite/go-carbon/commit/7337479972c84f22f1bea1f274b4c97e295e0a45
https://travis-ci.com/github/bookingcom/carbonapi/jobs/359660398
> github.com/lomik/go-carbon moved to github.com/go-graphite/go-carbon

- app/carbonapi/app.go
- app/carbonapi/routes.go
#214  What issue is this change attempting to solve?
Now that we have gorilla/mux we can `Use` middlewares.
This should also solve "HTTP GET route not found" from traces title.
Now that we can `Use` middlewares, this should be more readable compared to chaining them by hand.
Tested with prod traffic and by hand:
```
curl -H "Accept-Encoding: gzip" -I localhost:8091/render
...
Content-Encoding: gzip
```
> Router: start using middlewares

- app/carbonapi/app_test.go
If there is something else listening on port 8080, the test will fail.
If we use the default HTTPServer listener it will listen on 0 - that's
any available port.
> do not to listen on port 8080 in the tests

- app/carbonapi/app.go
- app/carbonapi/http_handlers.go
- app/carbonzipper/app.go
- app/carbonzipper/http_handlers.go
- pkg/trace/trace.go
traces: send errors as bool and put the actual error message in error.message
add also service.version tag so we know what version of carbonapi/zipper is generating the trace.
TIL that convention is to set the 'error' field to true for spans with
errors:
https://github.com/opentracing/specification/blob/master/semantic_conventions.md
> traces: send errors as bool 

- expr/types/types.go
errors: classify ErrWildcardNotAllowed and ErrTooManyArguments as
parsing errors
That way, we will answer with HTTP  400 instead of HTTP 500 when we encouter those errors.
Only reason we have them in this package is because we are doing this
validation during eval and not during parsing
make test
> classify ErrWildcardNotAllowed and ErrTooManyArguments as ParseError

- app/carbonapi/http_handlers.go
- cfg/common.go
When we get panics during evalExpression, we can see only the error
message, for example:
`index out of range [8] with length 2`
This makes it impossible to debug.
With the new option to print the stack trace, we can see where is the
error coming from
Tested on one server.
> carbonapi: add new config option `printErrorStackTrace`

- expr/functions/cairo/png/cairo.go
First fix: instead of consolidationg the consolidation, always
consolidate the original data.
Second fix: When there is no consolidation, we still need to set
ValuesPerPoint to 1. It it used later for computing the x coordinate,
and if we leave to 0 all x coordinated will be NaN(divison by zero).
I'm not very happy with this approach for the second fix, a better one would 
be to have a constructor for TimeSeries and set there the default value for
ValuesPerPoint to 1 there.
Tested by hand with cases where we have and where we don't have consolidation.
> Fixes for cairo consolidation

- expr/functions/asPercent/function.go
- expr/functions/asPercent/function_test.go
For this expression `asPercent(not_found_metric, found_metric)` we
would answer with http 5xx.
Now we answer with 404, Not Found.
I considered two possible solutions:
a) return empty timeseries array.
b) return types.ErrMetricsNotFound.
I opted for a) becuase this is what divideSeries is doing if first
argument is not found.
graphite python is answering with 5xx too. 
Added test.
> asPercent: return [] if the first argument is not found

- expr/expr_test.go
- pkg/parser/parser.go
add # to characters that can be part of a Name
I noticed this issue as an error when calling groupByNode("a.b#c.d", 1, 'sum').
This happened because ExtractMetricName would extract the name 'c.d' out of it.
It seems that we already have metrics with '#' in their name.
Added test.
> add # to characters that can be part of a Metric Name

- app/carbonapi/http_handlers.go
Sometimes we are wrapping the NotFound errors. If we use errors.As, we
can see that they are the same error type
That way, we answer with http 404 instead of 5xx for NotFound errors.
> errors: use errors.As for checking if an error is NotFound

- expr/functions/asPercent/function.go
- expr/functions/asPercent/function_test.go
- expr/functions/averageSeries/function.go
- expr/functions/divideSeries/function.go
- expr/functions/minMax/function.go
- expr/functions/percentileOfSeries/function.go
- expr/functions/seriesList/function.go
- expr/functions/stddevSeries/function.go
- expr/functions/sum/function.go
- expr/helper/combine.go
- expr/helper/helper.go
- expr/types/types.go
Rewrite asPercent to support metrics with different resolutions.
Part of this change:
- update signature of CombineSeries callback to return both (value,
isAbsent).
- added constructor for MetricData.
- updated AggregateSeries signature to received the name of the
resulting metric. 
Added new tests(imported from original graphite test suite).
> asPercent: rewrite to support different resolution metrics

- expr/functions/averageSeries/function.go
- expr/functions/legendValue/function.go
- expr/functions/minMax/function.go
- expr/functions/nPercentile/function.go
- expr/functions/percentileOfSeries/function.go
- expr/functions/removeBelowSeries/function.go
- expr/functions/sortBy/function.go
- expr/functions/stddevSeries/function.go
- expr/functions/sum/function.go
- expr/functions/summarize/function.go
- expr/helper/helper.go
- expr/helper/helper_test.go
- expr/helper/normalize.go
AggregateSeries: update callback function to return (value, isAbsent)
That way, it will be consistent with the rest of the API.
And now that we have a contructor for TimeSeries, we can use in
AggregateSeries()
make test
> AggregateSeries: update callback function to return (value, isAbsent)

- expr/helper/helper.go
If len(seriesList) == 0 and absent_if_first_series_absent we would try to access seriesList[0]
Just return [] if input is []
make test
> AggregateSeries: fix case when len(seriesList) == 0 and absent_if_first_series_absent

- expr/functions/holtWintersAberration/function.go
- expr/functions/holtWintersConfidenceBands/function.go
- expr/holtwinters/hw.go
We we trying to get data back in the past 7 days.
But sometimes we don't have all this data and we receive a shorter
timeseries.
Handle this case by computing how many datapoints we need and returning
this number of datapoins from the prediction
> holtwinters: fix Index error

- app/carbonapi/app_test.go
- app/carbonapi/http_handlers.go
grafana alerting has a special option on what to do "if data not found".
For this condition to be true, we have to answer with http 200 and [].
If we answer with http 404, this will be considered an error.
This is what graphite python answers on 'not found'.
> render: stop answering with HTTP 404

- app/carbonapi/http_handlers.go
During http request, we check if ctx.Done() and return with Err when
this happens.
But then when we collect results(and errors) we handle those context
deadline errors as regular errors.
For a complex request with 200k metrics,this is what happens:
- ~120k metrics are retrieved with sucess
- for the rest 80k metrics we received 'context deadline' errors
When merging those errors, we just drop the 'context deadline' errors
and continue operations with the remaining 120k metrics as if nothing
happened.
With this check, we just return ctx.Err() on ctx.Done()
tested with slow request.
> renderHandler: check if context.Done()

- pkg/backend/net/net.go
Fixes #239 
during one complex render request we can issue other 100k render
requests to the zipper.
After a while, they start reaching main context deadline.
When this happens, logs get poluted with tens of tousands of log lines.
I just removed the log lines.
Tested with slow request.
> bnet: remove context cancel logs

- app/carbonapi/app.go
- app/carbonzipper/app.go
#What issue is this change attempting to solve?
When processing a request, we use a ctx with a timeout that was
Timeout.Global value.
At the same time, we set the same Timeout as WriteTimeout when creating
the httpServer.
What happens it that after `Timeout.Global` seconds:
- we check if ctx.Done() and return from functions with errors.
- the http server is closing the connection because we reached
WriteTimeout
So when we try to answer with an error because we reached ctx.Deadline the connection will be closed.
I'm not 100% sure that 2*Timeout.Global is the right value here.
Idea is that WriteTimeout has to be greater than ctx.Deadline, so I though to use the double of that number.
Tested with very slow request that times out.
> WriteTimeout & ctx.Deadline race condition

- expr/functions/constantLine/function.go
- expr/functions/constantLine/function_test.go
- tests/helper.go
I was checking graphite-python and there constantLine has 3 datapoints.
This helps when we use functions with constantLine(). That way, the
result with have 2 datapoints(instead of one)
> constantLine: add one more datapoint

- expr/expr.go
evalExpr: test for context cancellation
If the clients goes away or of we reach the deadline we want to stop evaluating expressions.
I think this is a good spot for this check because this place is called for each function evaluation and for each argument of functions.
> evalExpr: check for context cancellation

- app/carbonapi/http_handlers.go
- app/carbonzipper/http_handlers.go
- pkg/backend/net/net.go
find: answer with http 422 for requests that are too complex
Removed ErrContextCancel type because it was not used and it made
errors.Is() checks to fail
Tested with very small timeout.
> find: answer with http 422 for requests that are too complex

- app/carbonapi/routes.go
- app/carbonzipper/routes.go
When trying to request /debug/pprof/heap I would get 404.
Since I used PathPrefix, we don't need the other paths individually.
Request to /debug/pprof/heap works now.
> pprof: fix routing

- cfg/common.go
- config/carbonapi.yaml
- config/carbonzipper.yaml
- pkg/trace/trace.go
I noticed that `carbonzipper` was running out of memory and getting OOM killed. 
A big chuck of memory was used by spans.
There are two options that control how many spans can get acumulated in memory:
`BatchMaxCount`(default 10) : maximum number of spans that get sent in a request.
`BufferMaxCount`(default 1 billion!) : maximum number of spans that can be stored in memory if sending is low.
Becuase of small `BatchMaxCount` spans would get send slow. Because of bug `BufferMaxCount`, the process would run out memory.
See also comment:
https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/trace/jaeger/jaeger.go#L136
I added two new options:  jaegerBufferMaxCount and jaegerBatchMax.
That way, we can configure max number of spans stored in memory and number of spans that …
> traces: add two new options:  jaegerBufferMaxCount and jaegerBatchMaxCount

- app/carbonapi/http_handlers.go
- app/carbonzipper/http_handlers.go
- pkg/backend/net/net.go
> return 404 instead of 500 when info-ing a non-existing metric

- pkg/parser/parser.go
This fixes a bug introduced in: 2f9c4cd9d606a65b5cdf15706011f19864f1ad3f.
For the `moving*` functions, default was to return `r` and not `nil`
I replaced the switch with an `if` because it had a single `case` anyway.
Tested and was not able to reproduce the bug.
> Fix bug introduced int:"linter: all 'switch' related issues"

- .github/workflows/ci.yml
- .golangci.yml
- AUTHORS.txt
- pkg/parser/interface.go
- pkg/parser/internal.go
- pkg/parser/parser.go
- pkg/parser/parser_test.go
In the current implementation, carbonapi returns `400` errors for queries like ns1.ns2.foo-[a b] or ns1.ns2.foo-{a, b}.
However, if these types of queries happened to be wrapped around within a function, like sumSeries, that accepts
metrics list, no errors are returned. As they are treated as individual metrics and sent to storage, storage would
returns 400 as well.
This commit fixes the issue, by generating a parser error if spaces and comma appears inappropriately within []/{}.
At the same time, nested range list (like [[]]) and unclosed ([/{) or unopened (]/}) ranges or value list are also
reported as errors, instead of treating them as proper query and forwarding them to storages.
As consequence of this change, some of the requests that are originally returning 200 would be returned …
> parser: return errors if there are syntax bugs in metric names wrapped by a function

- expr/functions/glue.go
- expr/functions/medianSeries/function.go
This is actually a fix for groupByNodes(path.to.metrics.*, "median", 3) as groupByNodes
implementation in carbonapi translates the query into `aliasByNode(medianSeries(path.to.metrics.*), 3)`.
There is no implementation of medianSeries in carbonapi atm.
A query like bellow now returns values instead of nothing:
```
groupByNodes(path.to.metrics.*, 'median', 3, 5)
```
> carbonapi: introduce new function medianSeries

- expr/expr.go
This fixes a regression caused by commit f74343ceb74500b9b4997470604cea6f135054eb.
Returns an error rather than a nil would be helpful for graphite functions to notice
that data does not exist and can return 4xx or 2xx, rather than panics and return
5xx.
500s are reduced.
> carbonapi/render: EvalExpr should return series no exist as error

- pkg/parser/parser.go
- pkg/parser/parser_test.go
This commit supports ignoring all whitespaces instead of only
ignoring spaces. The feature is beneficial because interfaces like
grafana allow multi-line queries.
The current proposed change uses `unicode.isSpace` instead of checking with space character. We could also re-implement it to be faster, but I do not believe it is a big deal.
> Support all whitespaces in carbonapi parser

- app/carbonzipper/app.go
- app/carbonzipper/http_handlers.go
- app/carbonzipper/metrics.go
- cfg/common.go
- docker/zipper/Dockerfile
- pkg/backend/benchmark_test.go
- pkg/backend/rpc.go
- pkg/backend/rpc_test.go
- pkg/types/types.go
- pkg/types/types_test.go
It is possible that metrics in different backends have different values for points (replica mismatches). These are mainly caused by aggregating metrics with null points. The null points on backends are also caused by backends being temporarily unavailable. 
`renderReplicaMatchMode` is introduced to configure carbonzipper on how it should behave on merging metrics retrieved from backends.
With `majority` implementation, for each of the data points in a render request result, the values stored in the majority of backends will be returned.
If there is no majority in the values, this code returns ~one of the most voted values~ the first value like normal mode (To be discussed).
Also, one counter is added for monitoring number of fixed mismatches. it is increased whenever a data-point has a …
> Add render majority read feature

- app/carbonzipper/app.go
- app/carbonzipper/http_handlers.go
- app/carbonzipper/metrics.go
It adds the metric to measure the number of render responses having mismatches in them (queries with inconsistency).
Simply adds a counter.
> Add mismatched render response metric

- app/carbonzipper/http_handlers.go
- cfg/common.go
- pkg/backend/benchmark_test.go
- pkg/backend/rpc.go
- pkg/backend/rpc_test.go
- pkg/types/types.go
- pkg/types/types_test.go
Because of the performance impact of float approximate checks, a
new config is introduced to determine if the floats should be
checked approximately or exactly.
The whole mismatch related configs are also encaped into one
struct.
Adds a bool config for approximate checks
> Add mismatch approximate float check config

- pkg/backend/benchmark_test.go
- pkg/types/types.go
Regarding the performance issues seen on majority read feature introduced in #348 on carbonzipper rendered replica metrics, this PR attempts to optimize the computation on merge functionality of zipper.
Using the [Boyer–Moore majority vote algorithm](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_majority_vote_algorithm) (proposed by @bom-d-van) The performance of majority voting is increased. The benchmark results (with new data) is presented:
before Boyer–Moore majority vote algorithm:
```
goos: linux
goarch: amd64
pkg: github.com/bookingcom/carbonapi/pkg/backend
cpu: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
BenchmarkRendersStorm/BenchmarkRendersStorm/ReplicaMatchMode-normalWithExactEqCheck-8         	       1	6052688709 ns/op …
```
> Optimize zipper majority vote

- pkg/types/types.go
There was a bug in the function. it was returning false instead of true in case of earlier majority.
> Fix bug in majority vote function

- docker/carbonapi/Dockerfile
- docker/go-carbon/Dockerfile
- docker/nanotube/Dockerfile
- docker/zipper/Dockerfile
The CI integration test is now failing because of the go version. 
This PR fixes this issue.
> Upgrade go version in dockerfiles

- .github/workflows/ci.yml
- Makefile
- app/carbonzipper/http_handlers_test.go
- pkg/parser/parser_test.go
Fixes #365 
See https://github.com/bookingcom/carbonapi/issues/365#issuecomment-1149804051 for details.
In addition:
* removed unnecessary `govet` as it is not part of testing and is run by `golangci-lint`,
* removed superfluous build during the test.
> Fixing errors in CI that succeeds.

- pkg/types/types.go
- tests/helper.go
Fixes #367 
This fixes the reported issue. However, we have a similar problem in other places. Also, https://github.com/bookingcom/carbonapi/blob/4eaed1b90740618bda6e5e3c3e23e5c2ed6df368/tests/helper.go#L143 has a number of flaws and we need to replace it.
IMO we also need to do some more investigation on the method we currently use before applying it across the project.
This is why this approach is only applied locally now.
Failing tests pass now.
> Corrected floats comparison in a test to take into account limited precison of floating point numbers.

- app/carbonapi/app.go
- app/carbonapi/http_handlers.go
- app/carbonzipper/http_handlers.go
- pkg/types/types.go
Client errors were producing error level logs which didn't make sense. This PR revises the log levels in carbonapi and carbonzipper.
> Refactor log levels

- app/carbonapi/http_handlers.go
- cfg/api.go
- cfg/api_test.go
- config/carbonapi.yaml
We have 3 parameters:
sendGlobsAsIs: true|false
alwaysSendGlobsAsIs: true|false
maxBatchSize: int
Their logic is convoluted
sendGlobsAsIs in true is working together with maxBatchSize
carbonapi is sending a find request and depending on amount of metrics returned from stores acts differently:
if amount of metrics is lower than maxBatchSize it sends request as is with globs
if amount of metrics is higher it uses list of metrics returned from find and query them one by one
sendGlobsAsIs in false is always sending find and ignoring maxBatchSize
alwaysSendGlobsAsIs is neglecting sendGlobsAsIs settings and always send a render request without 'find'
This commit is deprecating sendGlobsAsIs maxBatchSize and alwaysSendGlobsAsIs in favor of
resolveGlobs: int
resolveGlobs: = 0  -> send render …
> Refactor sendGlobsAsIs

- pkg/backend/net/grpc.go
For http backend client, we do not respect the http proxy environment, so we should do the same on gRPC.
> Use noproxy dial option on grpc client

- .github/workflows/ci.yml
Made linting a command instead of a separate job in CI.
Apparently, this fits better in the memory limits of GitHub actions and fixes #376
> Fixing CI lint OOM.

- app/carbonzipper/http_handlers.go
renderHandler of carbonzipper was using an incorrect
"find" label for a RequestCancel metric.
> carbonzipper(bug): add proper label to renderHandler

- app/carbonapi/http_handlers.go
All log lines should contain carbonapi_uuid field in order to
allow traceability of requests. This commit is changing one specific
line where this field was wrongly named "uuid" making harder to trace
"zipper returned error in find request" errors
> carbonapi(bug): fix UUID field in logs

- app/carbonzipper/app.go
- app/carbonzipper/http_handlers.go
- app/carbonzipper/http_handlers_test.go
- app/carbonzipper/metrics.go
- app/carbonzipper/routes.go
- app/carbonzipper/tldcache.go
- cmd/carbonzipper/main.go
- pkg/backend/benchmark_test.go
- pkg/backend/net/benchmark_test.go
- pkg/backend/net/net.go
- pkg/backend/net/net_test.go
- pkg/types/types.go
Note: This PR includes unfinished refactoring. Some rough edges are to be expected.
* Fixes time in queue for zipper stats.
* Refactoring/redesign of the zipper.
* Removed parts of the global state
* Partially removed expvars
* Restructured modules
* Misc cleanups
> Switched to a single labeled metric for the time in q in zipper. Start of zipper redesign.

- app/zipper/app.go
Previously, the goroutine for cache probing was never started.
> Fixed ordering of TLD cache update call.

- .golangci.yml
- pkg/app/zipper/app.go
- pkg/app/zipper/http_handlers.go
- pkg/app/zipper/metrics.go
- pkg/backend/net/grpc.go
- pkg/backend/net/net.go
- pkg/backend/rpc.go
- pkg/backend/rpc_test.go
- Introduced path cache filter metric: A counter to count the number of successful backend filters on zipper.
- Introduced backend status metric: A counterVec to count the status codes received from the storage backends.
- Added TimeInQueue histogram observation to gRPC backend calls as well as HTTP calls.
> Improve backend-related metrics in zipper

- config/carbonapi.yaml
- pkg/app/carbonapi/http_handlers.go
- pkg/cfg/api.go
For carbonapi. This parameter allows us to trigger usage of cache for render resolve globs (preflight find requests).
> Add 'enableCacheForRenderResolveGlobs' config param

- cmd/carbonzipper/main.go
- config/carbonzipper.yaml
- pkg/app/zipper/app.go
- pkg/app/zipper/http_handlers.go
- pkg/app/zipper/http_handlers_test.go
- pkg/app/zipper/tldcache.go
- pkg/app/zipper/tldcache_test.go
- pkg/backend/mock/mock.go
- pkg/cfg/common.go
This new config adds the functionality to probe deeper paths on zipper in order to involve less backends on queries when metrics are broken into different cluster from the non-leading namespaces.
In addition to normal TLD probes, probes with the configured prefixes are also sent. the results already gathered from the previous probes sent at the same iteration is used to optimize the backends receiving the probes.
New tests are introduced and the functionality is manually tested on local.
> Add tld cache extra prefixes to zipper

- expr/sort.go
- expr/sort_test.go
It's related to this PR https://github.com/go-graphite/carbonapi/issues/128. Before this change it's possible that query can have more dots than requested metric. Obvious example:
Metrics: 
```
a.b1.c.d
a.b2.c.d
a.b3.c.d
a.b4.c.d
```
Query: `a.{*.b1,*}.c.*`
Query looks strange, but it's valid and it was taken from real example. 
So, in the case above sorting will cause out of index error in `getPart()` function (and caused panic, intercepted only in http module, which is not good).
Instead of splitting query by dots using simple `strings.Split()` I'm splitting it by using tricky regex, which will ignore dots inside square or curly bracket pairs. In that case sort will work properly and will not cause errors in queries above. 
I also included range protection in getPart() but proper …
> Fixing out of index error during metric sorting

- expr/functions/cairo/png/cairo.go
Panic `invalid value (typically too big) for the size of the input (surface, pattern, etc.)` in cairo module, probably caused by abnormal image size. Cairo has [hardcoded](https://github.com/freedesktop/cairo/blob/929262dd54ffae81721ffe9b2c59faa7b045c663/src/cairo-image-surface.c#L59-L62) height/width limitation (should be less or equal than 32767 pixels).
```
2022/09/27 10:22:14 http: panic serving 127.0.0.1:33430: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
goroutine 75082862 [running]:
net/http.(*conn).serve.func1()
/usr/lib/golang/src/net/http/server.go:1825 +0xbf
panic({0xc97e60, 0x15a87a0})
/usr/lib/golang/src/runtime/panic.go:844 +0x258
github.com/evmar/gocairo/cairo.ImageSurfaceCreate(0xc0002008a0?, 0xd7b0c7?, 0x4?) …
```
> fixing panic in cairo because of abnormal image size

- cmd/carbonapi/main.go
- cmd/carbonzipper/main.go
- pkg/app/carbonapi/app.go
- pkg/app/carbonapi/http_handlers.go
- pkg/app/zipper/app.go
- pkg/app/zipper/http_handlers.go
- pkg/app/zipper/http_handlers_test.go
- pkg/app/zipper/metrics.go
- pkg/app/zipper/zipper.go
- pkg/cfg/api.go
*This is an intermediate stage in the re-design. There are a lot of temporary plugs that will be cleaned-up later. The design is work in progress and rough corners are to be expected.*
This merges `zipper` into `carbonapi`. They can now be run as a single binary if a corresponding option is set.
`carbonapi` will still use `zipper` as an external service by default.
`Zipper` features were transformed into a package that is used both by `zipper` and by `carbonapi`.
* Embedded `zipper` exposes its metrics along w/ `carbonapi` but prefixed w/ `zipper_`. This allows to monitor embedded `zipper` w/o conflicts, but it's temporary and will go away when the merge is done.
* Embedded `zipper` uses `carbonapi` logger w/ and additional mark. The mark is to be …
> Zipper can now be run as part of carbonapi.

- cmd/carbonapi/main.go
- pkg/app/carbonapi/app.go
- pkg/app/carbonapi/http_handlers.go
This prevents potential contention and other concurrency issues. The limiter will be removed or reworked after redesign is done.
> Added limiter for the render requests to the embedded zipper.

- pkg/app/carbonapi/http_handlers.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/carbonapipb/carbonapi.pb.go
Currently, there's no visibility over cache errors. This PR takes into account errors happened during set/get of cache.
It is ensured that the errors are escalated and caught on references. Then, errors are added to carbonapi request logs.
Tests are improved.
> Improve capi cache logic and logs

- cmd/carbonapi/main.go
- pkg/app/carbonapi/app.go
- pkg/app/carbonapi/app_test.go
- pkg/app/carbonapi/http_handlers.go
- pkg/app/carbonapi/metrics.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
Several observability additions:
* a set of metrics for carbonapi memcached. Fixes #241 
* metrics to count requests propagated to remotes from carbonapi
* added metrics to the zipper limiter in carbonapi
Also, added a limiter to find requests from carbonapi to zipper.
> Observability additions for carbonapi.

- pkg/app/carbonapi/app.go
- pkg/app/carbonapi/http_handlers.go
- pkg/app/carbonapi/metrics.go
- pkg/app/zipper/app.go
- pkg/app/zipper/metrics.go
- pkg/backend/net/grpc.go
- pkg/backend/net/net.go
- pkg/backend/net/net_test.go
- pkg/prioritylimiter/prioritylimiter.go
* Added a set of metrics for a limiter that covers carbonapi, standalone and embedded zipper.
* Added visibility to errors in HTTP requests to backends.
> Added observability to limiter and to errors in HTTP requests.

- pkg/app/carbonapi/app.go
- pkg/app/carbonapi/routes.go
- pkg/app/zipper/routes.go
- pkg/types/types.go
The cpu, trace and some other profiles cannot be obtained for carbonapi and zipper because the routing is broken.
We route as
```
r.PathPrefix("/debug/pprof").HandlerFunc(pprof.Index)
```
but this only serves part of the profiles, not all.
The routing is correctly set in the standard lib here https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/net/http/pprof/pprof.go;l=80
Tested locally and on a live box.
> Fixed routing of the pprof queries. Small refactoring.

- pkg/app/carbonapi/app.go
- pkg/app/carbonapi/app_test.go
- pkg/app/zipper/app.go
- pkg/app/zipper/http_handlers_test.go
- pkg/app/zipper/metrics.go
- pkg/app/zipper/tldcache_test.go
- pkg/backend/backend.go
- pkg/backend/benchmark_test.go
- pkg/backend/net/grpc.go
- pkg/backend/net/net.go
- pkg/backend/net/net_test.go
- pkg/backend/rpc.go
- pkg/backend/rpc_test.go
- pkg/cfg/common.go
*Disclaimer: This PR is part of a bigger refactoring. We had to make design compromises to accommodate both the old and the new processing systems at the same time. Once we completely switch to the new system, the design and code can be cleaned-up and ordered. Final touches are part of #407, and we'll do them before closing it.*
This is a continuation of #407
This PR contains the new implementation of the backend requests processing. The old backend limiters were removed and replaced with the new processing via queues. At the same time, the old top-level limiter in `carbonapi` still stays in place and will be removed at the later stages.
> Processing redesign: Redesigned the backend requests processing.

- pkg/app/carbonapi/app.go
- pkg/app/carbonapi/http_handlers.go
- pkg/app/carbonapi/metrics.go
- pkg/app/carbonapi/proc.go
- pkg/app/zipper/app.go
- pkg/app/zipper/zipper.go
- pkg/backend/backend.go
- pkg/backend/net/net.go
- pkg/backend/rpc.go
- pkg/cache/cache.go
- pkg/cfg/api.go
*Disclaimer: This PR is part of a bigger refactoring. We had to make design compromises to accommodate both the old and the new processing systems at the same time. Once we completely switch to the new system, the design and code can be cleaned-up and ordered. Final touches are part of #407, and we'll do them before closing it.*
This is a continuation of #407. The following changes were made:
* The old limiter is disabled in `carbonapi`;
* Timeout handling added to the top-level processing;
* Clean-up.
* The old limiter is still in place to avoid huge PRs.
* The `find` requests are not limited on the top level to give them higher priority.
* Some benchmark were removed as non-indicative for the current system.
> Processing redesign: Disabled old limiter in carbonapi. Added timeout handling.

- pkg/app/zipper/metrics.go
- pkg/app/zipper/tldcache.go
The metric can easily explode when using sub-domains. This would cause scraping overload and loss of visibility. Also, the metric is less valuable after introduction of sub-domains.
> Removed the TLD cache counter per domain.

- pkg/app/carbonapi/app.go
- pkg/app/carbonapi/http_handlers.go
- pkg/app/carbonapi/metrics.go
- pkg/app/carbonapi/proc.go
- pkg/app/zipper/app.go
- pkg/backend/net/net.go
- pkg/prioritylimiter/prioritylimiter.go
- pkg/prioritylimiter/prioritylimiter_test.go
This PR reverts part of the big recent changes to apply them in smaller steps and allow for additional improvements.
Also:
* Removed recently added req cancellation metric as non-indicative.
* Disabled additional cancellation during processing via timestamps. We will rely on context instead.
Part of #407 
> Processing redesign: Temporarily bring back the limiter to apply the changes in smaller stages.

- pkg/app/zipper/app.go
Currently, we close connections to zipper after 1s of inactivity. This results in connections thrashing and multiple connections hanging in `TIME_WAIT` state.
This change guarantees a stable set of connections between `carbonapi` and `zipper`, which is more efficient than the current constant connection recreation. Also, we get rid of thousands of connections hanging in `TIME_WAIT` state.
Tested on live traffic.
> Stabilize the set of connections to zipper. Disable closing connection after 1s of inactivity.

- pkg/expr/functions/stddevSeries/function.go
- pkg/expr/functions/stdev/function.go
Fixes #316 
Corrects the function usage to correspond to the intended design.
Tested locally and live with real-life queries.
> Fixed duplication of the stddev function identifier.

- pkg/app/carbonapi/app.go
- pkg/app/carbonapi/http_handlers.go
- pkg/app/carbonapi/metrics.go
- pkg/app/carbonapi/upstream.go
- pkg/backend/backend.go
- pkg/backend/benchmark_test.go
- pkg/backend/net/grpc.go
- pkg/backend/net/net.go
- pkg/backend/net/net_test.go
- pkg/backend/rpc.go
- pkg/types/types.go
Improved backend duration counting. Added duration counting for the find backend requests. Cleaned-up unused, duplicated (and sometimes wrong) metric counting with the Trace abstraction. Misc small cleanups.
Contributes to #436 #433 
> Misc metrics improvements and refactoring.

- pkg/types/encoding/json/encoding.go
- pkg/types/encoding/json/encoding_test.go
We're not setting `expandable` parameter in treejson same way as graphite-web does.
Currently we have [this code](https://github.com/bookingcom/carbonapi/blob/cc3581e0659bed151e3d5aa89b2be1b2824dc81a/pkg/types/encoding/json/encoding.go#L55-L63):
```go
if m.IsLeaf {
jm.Leaf = 1
} else {
jm.AllowChildren = 1
}
if !m.IsLeaf || strings.ContainsRune(jm.ID, '*') {
jm.Expandable = 1
}
```
I.e. we set expandable to true if it's not leaf and contain glob. Unfortunately, this implementation is logical, but wrong.
In graphite-web it's very simple - if it's leaf - then Leaf is true, else  AllowChildren and Expandable are true. See for example [this](https://github.com/graphite-project/graphite-web/blob/02bc0c836269e07b38175fbfe3b5689afc87b4fa/webapp/graphite/browser/views.py#L86-L95) and …
> carbonapi: wrong expandable implementation in find

- pkg/app/carbonapi/http_handlers.go
- pkg/app/carbonapi/http_handlers_test.go
Expand API (introduced in #449) was implemented wrong - query can be multiple parameter, i.e. you can call `?query=a.b&query=c.d` and API should accept and support it.
So, `expandHandler` accepting array of results now, so, tests were amended too.
Also I had some notes about implementation not addressed in #449 (regarding using interface{} and excessive allocations) which also was fixed. 
See above.
Before fixing tests I compared results with graphite-web with different queries' and flags' combinations.
> Fixing and refactoring /metric/expand API

- pkg/backend/backend.go
- pkg/backend/net/net.go
> Fixes labeling of the backend duration metrics.

- pkg/types/encoding/json/encoding.go
- pkg/types/encoding/json/encoding_test.go
This reverts commit 1065ff97792a75f75644018a295dac497e0a488b.
Reverting bugged bugfix. Need more investigation.
> Revert "fix(find): set expandable parameter same as graphite-web does"

- pkg/app/carbonapi/http_handlers.go
- tests/experimental/hurl/12-find.hurl
- tests/experimental/hurl/13-find.hurl
- tests/experimental/hurl/16-find.hurl
- tests/experimental/hurl/17-find.hurl
Did same refactor as [before](https://github.com/bookingcom/carbonapi/pull/449/commits/1b65927d3b68cd2cebda1ebc4226e9f6b2fd42b6), but with tests now, so, should work properly.
Please note following:
1. In graphite-web find API [supports](https://graphite.readthedocs.io/en/latest/metrics_api.html#metrics-find) only `treejson` and `completer` format. So, we extended this to almost the same level of support as /render has - we have protobuf, raw and pickle formats. This is not graphite-web compatible, that's a new thing introduced in carbonapi before.
2. Before raw format produces `Content-Type: raw` and json format produces `Content-Type: json` header, which was not compatible with existing [standard](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types). Now it …
> refactor(find): use writeResponse for writing dada

- docker/go-carbon/Dockerfile
- pkg/backend/net/grpc.go
- vendor/google.golang.org/grpc/encoding/gzip/gzip.go
- vendor/modules.txt
go-carbon carbonserver http already uses gzip compression. This PR adds the same compression to gRPC calls to carbonserver.
> Add gRPC gzip compression

- pkg/backend/net/grpc.go
This is related to https://github.com/go-graphite/go-carbon/pull/514.
The motivation is described there, however, It should have been applied mainly to carbonapi.
> Add gRPC large init window size

- pkg/app/carbonapi/app.go
- pkg/app/carbonapi/http_handlers.go
- pkg/app/carbonapi/upstream.go
- pkg/cfg/common.go
- pkg/tldcache/tldcache.go
To avoid request fanout to all backends when a target is not in tld cache.
> Add config to respond 404 when TLD cache miss

- pkg/tldcache/tldcache.go
With previous code, tldCache was never nil.
> Fix initial value of tldCache in filterByTLD func

- pkg/expr/functions/cairo/png/cairo.go
FIxing panic in carbonapi.
`http: panic serving 127.0.0.1:53106: invalid value (typically too big) for the size of the input (surface, pattern, etc.)`
I did previous change (see #400 ) for height and width, but looks like not enough.
> Limit pixelratio below  cairo limits

- pkg/app/carbonapi/http_handlers.go
- pkg/backend/backend.go
- pkg/backend/net/grpc.go
- pkg/backend/net/net.go
- pkg/carbonapipb/carbonapi.pb.go
- pkg/types/types.go
This PR adds a SourceClusters to metrics to identify the cluster the metric originated from. When merging the metrics from multiple upstreams, the result metric contains all of the backends involved for that metric in its SourceClusters. In the end, carbonapi, logs the request with all of the source clusters who contributed for gathering the metrics.
> Add source clusters to render logs

- pkg/expr/functions/cairo/png/cairo.go
```
http: panic serving 127.0.0.1:52522: logscale with minvalue <= 0
goroutine 1028267222 [running]:
net/http.(*conn).serve.func1()
/usr/lib64/go/src/net/http/server.go:1850 +0xbf
panic({0xc77d60, 0xeda080})
/usr/lib64/go/src/runtime/panic.go:890 +0x262
github.com/bookingcom/carbonapi/pkg/expr/functions/cairo/png.setupYAxis(0xc0e0967070, 0xc0de658480, {0xc0e34f2738
```
I replaced all panics in cairo module with proper errors which will be returned to user as HTTP 400 instead of 500
> Replace panics in cairo with proper errors

- pkg/app/carbonapi/http_handlers.go
- pkg/expr/types/types.go
- pkg/expr/types/types_test.go
```
http: panic serving 127.0.0.1:44020: runtime error: slice bounds out of range [:-9223372036854775808]
goroutine 1134454440 [running]:
net/http.(*conn).serve.func1()
/usr/lib64/go/src/net/http/server.go:1850 +0xbf
panic({0xd4bea0, 0xc3c0dc5b00})
/usr/lib64/go/src/runtime/panic.go:890 +0x262
github.com/bookingcom/carbonapi/pkg/expr/types.(*MetricData).Consolidate(0xc076caf520, 0x8000000000000000)
/usr/local/git_tree/gopath/src/github.com/bookingcom/carbonapi/pkg/expr/types/types.go:295 +0x6f0
github.com/bookingcom/carbonapi/pkg/expr/types.ConsolidateJSON(0x42b, {0xc1c75fbf00, 0xf, 0x2000100?})
/usr/local/git_tree/gopath/src/github.com/bookingcom/carbonapi/pkg/expr/types/types.go:130 +0x190
github.com/bookingcom/carbonapi/pkg/app/carbonapi.(*App).renderWriteBody(0xc00025b800?, …
```
> fix panic because integer overflow in valuesPerPoint

- pkg/app/carbonapi/http_handlers.go
The previous logic was not correct if there were some non-glob metrics in the render request. This commit fixes the issue by setting total_metrics_count after upstream rendering finishes.
> Set total_metrics_count log entry after renders

- pkg/expr/functions/cairo/png/cairo.go
- pkg/expr/functions/cairo/png/pixel_ratio.go
Looks like `cairo.ImageSurfaceCreate` can be called with the image size larger than the one allowed.
The maximum can be looked up e.g. here https://github.com/ImageMagick/cairo/blob/main/src/cairo-image-surface.c#L62
It's also mentioned in the mailing lists https://cairo.cairographics.narkive.com/Mkjwvkep/32k-limit-with-image-surface The lists are old, but seems like the limitation is still in place.
Added a check.
> Added check for the image size before calling cairo.

- pkg/expr/types/types.go
It's rare but still.
```
http: panic serving 127.0.0.1:44020: runtime error: slice bounds out of range [:-9223372036854775808]
goroutine 1134454440 [running]:
net/http.(*conn).serve.func1()
/usr/lib64/go/src/net/http/server.go:1850 +0xbf
panic({0xd4bea0, 0xc3c0dc5b00})
/usr/lib64/go/src/runtime/panic.go:890 +0x262
github.com/bookingcom/carbonapi/pkg/expr/types.(*MetricData).Consolidate(0xc076caf520, 0x8000000000000000)
/usr/local/git_tree/gopath/src/github.com/bookingcom/carbonapi/pkg/expr/types/types.go:295 +0x6f0
github.com/bookingcom/carbonapi/pkg/expr/types.ConsolidateJSON(0x42b, {0xc1c75fbf00, 0xf, 0x2000100?})
/usr/local/git_tree/gopath/src/github.com/bookingcom/carbonapi/pkg/expr/types/types.go:130 +0x190
github.com/bookingcom/carbonapi/pkg/app/carbonapi.(*App).renderWriteBody(0xc00 …
```
> Another attempt to fix Consolidate panic

- pkg/expr/types/types.go
Recovered panic `index out of range [1] with length 1` when we have fewer elements in absent results than normal results:
`github.com/bookingcom/carbonapi/pkg/expr/types.MarshalJSON({0xc19c012c48, 0x3, 0x3?})
/usr/local/git_tree/gopath/src/github.com/bookingcom/carbonapi/pkg/expr/types/types.go:169 +0x4bd`
Let's check array size beforehand
> Checking absent array size during marshaling

- pkg/expr/expr_test.go
- pkg/expr/functions/legendValue/function.go
Sometimes it is useful to print values (current, min, max, average) in the graph legend in human readable form.
Unfortunately, legendValue function of carbonapi is only able to print the raw values, because the systems "si" and "binary" are not implemented yet.
This PR implements the "si" and "binary" system for the legendValue function, it is currently running on my productive environment without any issues.
Please let me know if you have any questions or remarks.
> Implement si and binary system for legendValue

- pkg/expr/functions/timeLag/function.go
- pkg/expr/functions/timeLag/function_test.go
TimeSeriesLag function calculates time-based lag (e.g. for Kafka offsets) based on two offsets metrics - consumer and producer.
Currently the lag function has a bug that produces negative values in some cases.
This MR simplifies and updates the logic of the function, and fixes this bug.
Code changes make the logic of lag calculation more understandable and account for the bug that was producing the negative values
Additional tests were added, broken tests were fixed
> TimeLagSeries function fix

- pkg/parser/interval.go
- pkg/parser/interval_test.go
Panic in interval.go when interval is empty
Backporting [fix](https://github.com/go-graphite/carbonapi/commit/3dfe0404f0f76994d806cb7ba4a4170e11e8660d#diff-bf4c665f5b3470f030914d05395c1b1140e49cc1dcbf1e071ad5361a3da2d5a8) from carbonapi 
Tests are also ported.
> check for empty interval string

- pkg/backend/backend.go
This is a bug fix. Previously, the secondly histogram was counted in nanoseconds instead of seconds.
> Added conversion to seconds for the time in back-end queue durations.

- pkg/app/carbonapi/http_handlers.go
- pkg/expr/functions/averageSeriesWithWildcards/function.go
- pkg/expr/functions/multiplySeriesWithWildcards/function.go
- pkg/expr/functions/multiplySeriesWithWildcards/function_test.go
- pkg/expr/functions/sumSeriesWithWildcards/function.go
- pkg/expr/functions/sumSeriesWithWildcards/function_test.go
- pkg/expr/helper/helper.go
This PR aims to fix sizing problems of `*WithWildcards` functions.
A new helper function is introduced to avoid duplications.
The implementation of the function (`AggregateSeriesWithWildcards`) follows the pattern that helper `AggregateSeries` function is implemented with.
> Fix with wildcards functions panic
