bookingcom/carbonapi

cmd/carbonzipper/main.go
There are still some problems to be worked out here. For one,
graphite-web is unhappy about these changes. Until we can debug this
properly, let's revert the changes so master will be in decent shape.
=> Revert pkg/backend integration in Zipper

expr/helper/helper.go
Improved error handling to remove panics in case of empty results.
=> Fix panic in case of empty result.

app/carbonapi/http_handlers.go
=> Add carbonapi_uuid to http response header

.gitignore, .travis.yml, Makefile, README.md
Fixes #31 
* added codecov.io test coverage report
* upd README with a badge
* upd gitignore with coverage report
* changed test coverage config to fit the codecov
=> Added codecov test coverage reporting

pkg/backend/net/net.go
=> Added logging when context is cancelled/timed-out

Makefile
=> Added back cairo tags

COMPATIBILITY.md, expr/functions/cairo/png/cairo.go, expr/functions/cairo/png/picture_params.go, expr/functions/cairo/png/pixel_ratio.go
Cherry picking https://github.com/go-graphite/carbonapi/pull/364/.
=> pixelRatio param for render with format=png

expr/functions/cactiStyle/function.go, expr/functions/ewma/function.go, expr/functions/kolmogorovSmirnovTest2/function.go, expr/functions/pearson/function.go, expr/functions/pearsonClosest/function.go
This change makes all the formatting correct in the project.
After this is merged we will be able to add formatting check to CI.
=> Fixed formatting in the whole project to conform to gofmt

COMPATIBILITY.md
=> Updated the compatibility information between graphite-web and carbonapi

app/carbonzipper/metrics.go
=> Fixed typo in Prom metric name

README.md
=> Updated readme with supported cairo version

app/carbonapi/app.go, app/carbonapi/http_handlers.go, app/carbonapi/metrics.go, app/carbonzipper/http_handlers.go
=> Added response tagging by cached or no. Refactored http code logging

tests/generate_ts_metrics.py
This script writes a (time, path, value) row for each datapoint, which can be used to feed in data to different backends. This feeder needs to be added as well.
=> Add script which generates metrics for load testing

tests/gen_synthetic_reads.py
. This file is a straightforward one containing requests to query backends
directly.
=> Add script to generate a sample read requests file

README.md
=> Added info about Clickhouse support info to the README

app/carbonzipper/handlers_test.go
Simple test to verify errors are passed through
=> carbonzipper TestFindSingleBackendWithError

.travis.yml, Makefile
The convention is to use `check` keyword for testing command in Makefile. Thanks, @ericherman for pointing this out.
=> Changed testing target name in Makefile

tests/system_test.sh
This is how it works:
- brings up docker-compose with go-carbon as backend
- sends single value to go-carbon
- reads it from api
- checks if it's really there
=> Added simple system test.

app/carbonzipper/app.go, app/carbonzipper/http_handlers.go, app/carbonzipper/metrics.go, config/carbonzipper.yaml, config/clickhouse/carbonzipper.yaml, docker-compose.yaml, docker/zipper/Dockerfile
see commit messages for details
=> Added not-found metric to zipper founds, config and docker improvements

app/carbonapi/app.go, cfg/common.go, cfg/common_test.go
see commit messages for detail
=> No graphite proxy by default + no block rules file is empty set of rules

pkg/types/encoding/json/encoding.go, pkg/types/encoding/json/encoding_test.go
=> Added sorting when returning json response in api

app/carbonapi/app.go, app/carbonapi/http_handlers.go
=> Fixed prometheus error counding in a copule of places

app/carbonapi/app.go, app/carbonapi/http_handlers.go, app/carbonapi/metrics.go
=> Render handler refactoring, started moving expvars to init()

app/carbonapi/app.go, app/carbonapi/app_test.go, app/carbonapi/http_handlers.go, app/carbonapi/http_handlers_test.go, app/carbonapi/metrics.go, carbonapipb/carbonapi.pb.go, expr/functions/cairo/png/cairo.go, expr/functions/cairo/png/png.go
see commit messages for more details
=> Error policy change

app/carbonapi/http_handlers.go
=> Now png resonses are returned with appropriate error codes

app/carbonzipper/handlers_test.go, app/carbonzipper/http_handlers.go
=> Changed error merge logic in case of all errors from backends to zipper: now we return 500 iff majority of backends return 500

config/carbonapi.yaml
=> Clarification of config parameters and they use/defaults

.codecov.yml
=> Disabled codecov comments in PRs. They give misleading info more often than not

app/carbonzipper/app.go, app/carbonzipper/http_handlers.go, app/carbonzipper/metrics.go, pkg/backend/net/net.go, pkg/types/types.go
=> Added outbound request durartion counting to zipper

app/carbonapi/http_handlers.go
=> Changed the context cancellation counting in api to only count top-level cancels. This way we can reason about QPS vs cancels

.travis.yml, README.md
For now, I just added the CI check to see if everything builds fine. More changes to follow. This is a draft PR.
=> Upgrade to go 1.12

app/carbonapi/app.go, cmd/carbonapi/main.go, config/carbonapi.yaml
- Added panic recovery per HTTP handler
- Added global panic logging and recovery in api
Fixes #163
=> Added panic recoveries and logging in api

app/carbonapi/http_handlers.go
This bug ensured that cached requests were not getting instrumented as part of latency metrics taking heaviness of requests into account, including per point pulled latency metrics.
=> Move defer to before cached requests return

Gopkg.lock, Gopkg.toml
=> Manually removed dependency on spf13/viper. Upd dep config format

tests/system_test.sh
This one fixes [Small improvements required in the system test #210](https://github.com/bookingcom/carbonapi/issues/210)
=> On the issue #210

app/carbonapi/app.go, app/carbonapi/http_handlers.go, app/carbonapi/metrics.go, cfg/common.go, cfg/common_test.go
=> Add prometheus metric for find request linear histogram breakdown

app/carbonapi/app.go, app/carbonzipper/app.go
So we have better visibility over gracehttp
=> gracehttp usage: improve logging

expr/expr_test.go, expr/rewrite/applyByNode/function.go
=> Changed indexing of applyByNode function to start from zero instead of 1

expr/functions/aliasSub/function.go, expr/functions/exclude/function.go, expr/functions/grep/function.go
So we answer with http 400 instead of 500
=> mark regexp compilation errors as InvalidArgument

expr/functions/holtWintersAberration/function.go
holtWintersAberration: fix index out of range error
The fix is similar with #304 
Tested with query that was failing.
=> holtWintersAberration: fix index out of range error

app/carbonapi/http_handlers.go
traces: answer with consistent error tags
=> trace: answer with consistent error tags

.github/CODEOWNERS
=> Upd codeowners.

app/carbonapi/http_handlers.go
Continue query execution even though no metric is found in prefetch as there are Graphite query functions that are able
to handle no data and users expect proper result returned. Example:
fallbackSeries(metric.not.exist, constantLine(1))
Refrence behaviour in graphite-web: https://github.com/graphite-project/graphite-web/blob/1.1.8/webapp/graphite/render/evaluator.py#L14-L46
This change ignores not found errors from pre-fretch and continue query execution.
Query like the one bellow now returns result instead of nothing:
```
fallbackSeries(metric.not.exist, constantLine(1))
```
=> carbonapi/render: continue query exection instead of not found/404

app/carbonapi/app.go
The original tz config only supports offset format like "UTC+1,3600", which is less handy
if carbonapi is deployed in areas that has daylight saving time. This commit makes carbonapi
support IANA time zone names.
This change supports both offset and iana names.
Set `tz` in carbonapi to "Europe/Amsterdam" or other timezone names and restart carbonapi. Make a query with from/to using format `HH:MM_YYYYMMDD`.
=> carbonapi/config: support setting tz with IANA Time Zone names, like "Europe/Amsterdam"

app/carbonapi/http_handlers.go
This fixes a regression caused by commit f74343ceb74500b9b4997470604cea6f135054eb.
By not treating series not found as error. 
It would be nice to return the error message, but it seems we do not have a way
to communicate it to grafana unless failing all the other queries in the same request.
* https://github.com/grafana/grafana/blob/v7.5.10/pkg/tsdb/graphite/types.go\#L5-L8
* https://github.com/grafana/grafana/blob/v7.5.10/pkg/tsdb/graphite/graphite.go\#L162-L167
Query fetching existing and non-existing metrics continue to work.
```
from=-3h&until=now&format=json&maxDataPoints=1368&target=path.to.metrics.0&target=path.to.metrics.1&target=path.to.metrics.not-exists
```
=> carbonapi/render: do not return error for parser.ErrSeriesDoesNotExist

pkg/types/types.go
Better logs for mismatches; only log mismatches visible to users.
By changing the logging from mismatches to unfixed mismatches.
=> Change mismatch logs to contain unfixed ones

.github/CODEOWNERS
=> fix(CODEOWNERS): fix Denys's username

.codecov.yml, .github/workflows/ci.yml, AUTHORS.txt, Makefile, README.md
Please see the descriptions of commits for more info.
=> Misc fixes.

pkg/backend/net/grpc.go
This PR adds gRPC find and info methods for gRPC backends.
=> Add info and find for gRPC backend

Makefile, tests/system_test.sh
* test runs on Mac now
* test is not CI-system-specific
* corrected shell style and improved safety
* added the makefile target
=> Polished e2e system test. Added to makefile.

pkg/app/carbonapi/http_handlers.go
Cache read globs in carbonapi omit preflight find request to zipper and the backend caches are not updated accordingly.
In order to populate backend caches in carbonzipper, we send the preflight find request to backends when the resolved globs are more than limit causing the globs to be broken. This is crucial for performance and avoids unnecessary overload.
=> Send find when huge globs are read from cache

pkg/types/types.go
Logs will allow to track metrics with schema mismatch
=> Added logs in zipper when metrics schema mismatch

Makefile, cmd/carbonapi/main.go, pkg/app/carbonapi/app.go, pkg/app/carbonapi/app_test.go, pkg/app/carbonapi/http_handlers.go, pkg/app/carbonapi/metrics.go, pkg/app/carbonapi/proc.go, pkg/cfg/api.go
This PR contains the top level processor of the new request processing system together with the necessary observability. This is an intermediate stage of refactoring and the design will be finished in the follow-up PRs.
Please check the comments in the code for technical details.
This is the first stage of solving the #407 and #35
The old limiter is kept in place for now. This way we can be sure the transition is smooth. It will be removed during the next stages.
The following steps will also introduce the new backend limiter in `zipper`.
This was extensively tested locally and on live boxes. The tests show that the latency performance is at least as good as before.
At the same time, **the peak number of goroutines is reduced approximately x20 times**.
=> First part of the new processing system.

pkg/app/carbonapi/proc.go, pkg/backend/backend.go
*Disclaimer: This PR is part of a bigger refactoring. We had to make design compromises to accommodate both the old and the new processing systems at the same time. Once we completely switch to the new system, the design and code can be cleaned-up and ordered. Final touches are part of #407, and we'll do them before closing it.*
This optimizes the requests processing and allows to safely remove the old limiter.
The threshold for large requests is intentionally hardcoded in `zipper` for three reasons. First, it's configuration would clash with `carbonapi`. Second, corresponding config is already available in `carbonapi` and will become available for `zipper` after merge. Third, I hope this approach will be simplified after carbonapi-zipper merged.
This change allows to reduce the number of …
=> Processing redesign: Prioritized lightweight requests in processing. Added handling of cancelled contexts.

config/carbonapi.yaml, config/carbonzipper.yaml, docker/carbonapi/Dockerfile, docker/carbonapi/carbonapi.yaml, docker/carbonapi/carbonzipper.yaml, expr/functions/glue.go, expr/metadata/metadata.go, pkg/app/carbonapi/app.go, pkg/app/carbonapi/metrics.go, pkg/app/zipper/app.go, pkg/app/zipper/metrics.go, pkg/app/zipper/tldcache.go, pkg/app/zipper/zipper.go, pkg/backend/net/net.go, pkg/cfg/api.go, pkg/cfg/common.go
Please see commit messages for details.
This contributes to #433 #431 #432 
Fixes #434 
=> Continuation of redesign and refactoring.

cmd/carbonapi/main.go, pkg/app/carbonapi/app.go, pkg/app/carbonapi/metrics.go
=> Added version flag and version metric.

docker/carbonapi/Dockerfile
=> Fixed integration test in Docker to use the correct config.

pkg/app/carbonapi/http_handlers.go, pkg/types/encoding/json/encoding.go, pkg/types/encoding/json/encoding_test.go
Fixing find functionality 
PR #451 was innocent, applying it back. Find was broken because of issue introduced in writeResponse refactor, I rolled it back. Probably, we need to improve our testing first.
=> Making find work again

pkg/backend/net/grpc.go
Currently, the minimum durations are used. They should probably be configurable.
=> Add gRPC keepalive client paramaters

pkg/app/carbonapi/http_handlers.go
This PR adds the functionality to send upstream render requests simultaneously. Before this, the procedure was sequential i.e. for a query like `sumSeries(A,B,C,D)`, it would take `upstream_response_time(A) + upstream_response_time(B) + upstream_response_time(C) + upstream_response_time(D)` to finish. With this change, the same query roughly takes `max(upstream_response_time(A), upstream_response_time(B), upstream_response_time(C), upstream_response_time(D))` to finish.
There are a few points which were ignored for the sake of simplicity:
- For globs, usually a find request is sent. These requests are not taken into account in this PR.
- The same parallelization can be done for all of the targets, but this PR only parallelizes renders in a single target expr.
=> Parallelize expr metrics upstream render reqs

.github/workflows/ci.yml, Makefile, docker/carbonapi/Dockerfile, docker/go-carbon/Dockerfile, go.mod
* Upgrading go to 1.20
* Upgrading linter and taming its memory appetites
=> Upgrading go to 1.20

pkg/expr/functions/cairo/png/cairo.go, pkg/expr/functions/cairo/png/pixel_ratio.go
Cleaning up old fix for cairo params because proper fix is done by @grzkv in https://github.com/bookingcom/carbonapi/pull/483
=> Removing old cairo fix

.github/workflows/ci.yml, docker/carbonapi/Dockerfile, docker/go-carbon/Dockerfile
- Adding stable and head Go versions to test
- Removing lint installer
- update lint version
=> Refreshing tests

.github/workflows/ci.yml
Removing 1.20, adding 1.22 and 1.23
=> Fix go versions

.github/workflows/ci.yml, go.mod, go.sum, pkg/blocker/requestblocker_test.go, tests/system_test.sh
=> Fix tests, upgrade actions

pkg/app/carbonapi/http_handlers.go, pkg/cfg/api.go
=> Added a threshold parameter to differentiate simple vs complex requests.
